TEAM-SEONYAK/SEONYAK_CLIENT

package.json, src/pages/login/LoginPage.tsx, tsconfig.app.json, vite.config.ts, yarn.lock
Closes #53 
요랬던게 
```ts
import GoogleIc from '../../../../assets/svgs/googleLogoIc.svg?react';
import theme from '../../styles/theme';
```
요래댔음당
```ts
import GoogleIc from '@assets/svgs/googleLogoIc.svg?react';
import theme from '@styles/theme';
```
`vite-tsconfig-paths`는 vite 빌더가 저희가 설정한 별칭경로를 알아먹게 해주는 플러그인입니다 ~
=> [ Setting ] alias 설정 

.stylelintrc, package.json, src/pages/juniorPromise/components/CustomCalendar.tsx, src/pages/juniorPromise/utils/getTomorrow.ts, yarn.lock
Closes #63
https://www.npmjs.com/package/react-calendar
📍 onChange는 날짜가 변경되었을 때 호출되는 함수입니다. 사용자가 달력에서 날짜를 선택할 때마다 이 함수가 호출되어 선택된 날짜가 value로 전달됩니다.
📍 value는 현재 선택된 날짜 또는 날짜 범위입니다. 단일 날짜 또는 날짜 배열을 지원하며, 캘린더가 이 값에 따라 초기 선택 상태를 표시합니다.
📍 minDate는 선택할 수 있는 최소 날짜를 지정합니다. 
📍 calendarType은 달력의 유형을 설정합니다. 주가 월요일부터 시작합니다.
```
<StyledCalendar
onChange={onChange}
value={value}
minDate={new Date()}
next2Label={null}
prev2Label={null}
showNeighboringMonth={false}
calendarType={'iso8601'}
defaultValue={[new Date(2024, 7, 1), new Date(2024, 7, 1)]}
formatDay={(locale, date) => date.getDate().toString()}
tileDisabled={tileDisabled}
tileClassName={tileClassName}
/>
```
규칙 :`.react-calendar__` 접두사에 뒤의 명령어 붙이기. 개발자 도구로 확인하면서 구현할 수 있었습니다!
ex)
- `.react-calendar__navigation`: 캘린더 내비게이션 바 스타일링.
- …
=> [ Design ] 후배_약속날짜 선택 캘린더 퍼블리싱

src/components/commons/FullButton.tsx, src/pages/onboarding/OnboardingPage.tsx, src/pages/onboarding/components/Layout.tsx, src/pages/onboarding/components/SelectBox.tsx, src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx, src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx, src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx, src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx, src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx, src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx, src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step인증완료.tsx, src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx, src/pages/onboarding/components/seniorOnboarding/Step재직인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
Closes #67 
```
1. 약관동의 : 필수 약관 체크 박스가 모두 채워졌을 때 
2. 개인정보입력 : 닉네임 중복 확인 결과 적절한 닉네임이면 활성화
3. 학교선택 : 학교 선택 완료 시 활성화
4. 계열선택 : 계열 1개 체크 시 활성화
5. 학과선택 :  최소 1개 학과 선택 완료시 활성화
6. 졸업인증 : 적절한 파일 첨부 완료 시 활성화
7. 명함인증 : 활성화 
8. 인증완료 : 둘다 활성화 
9. 직무선택 : 직무 선택 시 활성화
10. 재직기한 : 연차 선택 시 활성화
11. 번호입력 : 5번 필드에 고객이 인증 코드 4자리 입력하면 활성화
```
이렇게 CTA 활성화 조건인데, 서버 통신 결과에 따라 보여지는 애들이 있어서 임시 변수 만들어서 두었습니다. 
뒷단계는 대부분 서버통신이랑 연관되어있어서, 일단 어거지로 구현할 수 있는 부분만 했어요!!
https://github.com/user-attachments/assets/303ded3c-4031-4bb1-86a4-7df15924208d
=> [ Feat ] CTA 관련 조건부 렌더링 

src/components/commons/FullButton.tsx, src/components/commons/modal/BtnModal.tsx, src/pages/onboarding/OnboardingPage.tsx, src/pages/onboarding/components/Layout.tsx, src/pages/onboarding/components/SelectBox.tsx, src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx, src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx, src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx, src/pages/onboarding/components/commonOnboarding/Step약관동의.tsx, src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx, src/pages/onboarding/components/commonOnboarding/Step학교선택.tsx, src/pages/onboarding/components/seniorOnboarding/Step명함인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step인증완료.tsx, src/pages/onboarding/components/seniorOnboarding/Step재직기간.tsx, src/pages/onboarding/components/seniorOnboarding/Step재직인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx, src/pages/onboarding/components/seniorOnboarding/Step직무선택.tsx
Closes #110 
아직 이전 CTA PR 코리를 못받아서 일단 새 브랜치에 CTA 브랜치 작업물 pull 받아서 진행했습니다. 
이후 CTA PR develop으로 머지하면, 여기 PR에 잡힌 무관한 commit들 싹 정리될거에요! 
그전까지 참고하실 부분은 
[시작 커밋](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/commit/852af0bd6662ea513540124737c8a8f70cf9eb78) ~ [끝 커밋](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/commit/e741c4c64b0550879138381c2c803a0b3b5a2b95)
제 뷰에서는 모달의 CTA가 `button` 이 아닌, `input type="file"`이어야 해요. 따라서 type prop을 또 따로 뚫어줄까하다가, 어차피 chilren이 뚫려있으니 그냥 특별한 버튼 만들땐 직접 만들어서 children으로 넘겨주도록 하는게 확장성에 좋겠다 싶었어요. 
따라서 기존에 필수 prop이었던 btnText를 optional로 바꿔주고, btnText의 유무에 따라 모달 내 버튼을 조건부 렌더링 시켜주도록 수정했습니다. 
[관련 commit](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/commit/f461013a4216a23372de2fe39631efbb91829320)
-> 이렇게 하면 btnText를 주지 않을 경우 모달 내 버튼을 제거해줄 수 있고, chilren으로 직접 만든 button 넘겨주면 …
=> [ Feat ] 명함 인증 단계 기능 구현 

src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx, src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx, src/pages/onboarding/components/seniorOnboarding/Step졸업인증.tsx, src/pages/onboarding/constants.ts
Closes #113 
학과 최대 선택 가능 개수가 3개였는데, 1개로 줄었어요. 
이에 따라 관련된 라이팅 수정하였습니다. 
기존에는 칩 하나를 클릭하면 콘솔에 미친듯이 워닝이 떴어요 (수백개 우다다다다다) 
그 이유는 의존성 배열에 `selectedMajors`가 있는데, useEffect 내부에서 또 `selectedMajors`를 setState 시켜주고 있어서 무한 렌더링이 발생하는 문제였습니다. 
따라서 useEffect 내부에서 업데이트 시켜주고 있던 코드를 지워주고 정상 작동하도록 정리 좀 해줬습니다. 
추가로, 기존에는 칩이 생겼다가 사라졌다가 할 때 워닝 텍스트가 보기 좋지 않게 깜빡였는데, 
이부분도 조건부 렌더링 영역을 수정해줌으로써 해결해서 깔끔하게 생겼다/사라지도록 수정했습니다. 
https://github.com/user-attachments/assets/5f8f1651-b520-4174-bd57-6cc562fe9f03
=> [ Fix ] 학과 검색 뷰 고도화 

src/components/commons/seniorCard/SeniorCard.tsx, src/pages/seniorProfile/components/Example.tsx
Closes #186 
✅ SeniorCard를 사용하는 구조가 달랐습니다. 
- 최종 구조
- : JuniorPromisePage
` <SeniorListWrapper>
{seniorList?.map((list) => (
<SeniorCard
key={list.seniorId}
nickname={list.nickname}
company={list.company}
image={list.image}
field={list.field}
position={list.position}
detailPosition={list.detailPosition}
level={list.level}
variant="secondary"
/>
))}
</SeniorListWrapper>`
-: ExamplePage
`<SeniorListWrapper>
{dummayData.map((d, idx) => (
<CardWrapper key={idx} onClick={() => handleCardClick(idx + 24)}>
<SeniorCard
nickname={d?.nickname + ''}
company={d?.company + ''}
field={d?.field + ''}
position={d?.position + ''}
detailPosition={d?.detailPosition + ''}
level={d?.level + ''}
variant="secondary"
image="/image"
/>
</CardWrapper>
))}
</SeniorListWrapper>`
=> [ fix ] SeniorCard 레이아웃 조정

.prettierrc, package.json, src/Router.tsx, src/main.tsx, src/pages/join/JoinPage.tsx, src/pages/join/components/Welcome.tsx, src/pages/juniorPromise/JuniorPromisePage.tsx, src/pages/login/LoginCallback.tsx, src/pages/login/SignupPage.tsx, src/pages/login/apis/loginAxios.ts, src/pages/login/hooks/useGoogleLoginMutation.ts, src/pages/login/hooks/useLoginQuery.ts, src/pages/login/utils/googleLogin.ts, src/pages/onboarding/apis/joinAxios.ts, src/pages/onboarding/components/Layout.tsx, src/pages/onboarding/hooks/useJoinQuery.ts, src/pages/onboarding/type.ts, src/pages/promiseList/PromiseListPage.tsx, src/utils/apis/index.ts, yarn.lock
Closes #213 
1️⃣ **`https://accounts.google.com/o/oauth2/v2/auth` 로 접속** 
- query string : 
- client_id : 서버가 구글에서 발급받아서 전해준 CLIENT_ID
- redirect_uri : 서버가 구글에 등록하고 알려준 REDIRECT_URI 
- response_type : code (인가코드 받겠다는 뜻) 
- scope : email (로그인 성공 시 구글에서 제공하는 회원 정보 중 이메일만 받겠다는 뜻) 
이 주소로 이동시키기 위해서 로그인/회원가입 버튼 클릭 시 아래의 login 함수를 클릭이벤트핸들러로 연결해줘요. 
```tsx
const login = () => {
window.location.href = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${import.meta.env.VITE_APP_GOOGLE_CLIENT_ID}&redirect_uri=${import.meta.env.VITE_APP_GOOGLE_AUTH_REDIRECT_URI}&response_type=code&scope=email`;
};
```
> 여기서 VITE_APP_GOOGLE_CLIENT_ID, VITE_AP_GOOGLE_AUTH_REDIRECT_URI 는 서버가 구글 대시보드에 등록한 후, 저희에게 전달해주는 정보들입니다! 받아서 넣어주기만 하면 돼요 
위 주소로 접속하면 우리가 흔히 아는 **구글로그인 화면**으로 이동돼요.
해당 화면에서 구글 로그인을 **성공**하면, 사용자 …
=> [Fix] 구글 소셜 로그인 라이브러리 없이 구현 및 회원가입 플로우 문제 해결

src/pages/promiseList/components/RecentCard.tsx
Closes #219 
- 추출한 svg가 아이폰 SE에만 맞는 사이즈여서 모든 부분에서 전체 사이즈 차지하도록 변경했습니다 ~
- 너무 간단한 거라 없음
- 간단한 거라 걍 다 담 ㅋ
https://github.com/user-attachments/assets/a2d28200-aba0-4996-8f43-2ac946db3da7
=> [ design ] 후배 약속 리스트 - 텅 뷰 가운데 정렬

src/hooks/seniorProfileQueries.ts, src/pages/juniorPromise/JuniorPromisePage.tsx, src/pages/juniorPromise/components/FilterButton.tsx, src/pages/juniorPromise/components/SeniorListBackground.tsx
Closes #215 
우선.. pr이 이렇게 짧아도 되나.. 걱정되지만,, 일단 오늘치 리팩토링한 부분 pr 올려봅니다..!!
1️⃣ 프롭스 제거_positionChipNum
저의 부분은 field, position 두 개의 필터에 대해 동일한 로직이 2번씩 반복되는 데요..
field는 가지지않는 position만 있는 props입니다.
선택된 직무의 개수에따라 숫자가 변하는 부분입니다!
```typescript
// 선택된 직무 칩 수
const getPositionTrueNum = (arrPosition: boolean[]) => {
return arrPosition.filter((n) => n).length;
};
const positionChipNum = getPositionTrueNum(arrPosition);
```
요놈인데요.. 
field의 경우
```typescript
// 칩으로 나갈 선택된 계열 이름 리스트
const [chipFieldName, setChipFieldName] = useState<string[]>([]);
```
이 배열의 길이로 숫자를 적용해서, position도 동일하게 바꾸었습니다..! 자자잔
```typescript
{chipPositionName.length > 0 && <ChipNum>{chipPositionName.length}</ChipNum>}
```
이상입니다,, 오늘치 리팩토링이고 다음번 pr은 좀 더 옹골찬 props사망사건으로 찾아뵙겠습니다.. 총총..
2️⃣ 필터 적용시 깜빡임 제거
아래 첫번째 동영상 보시면 바텀시트 내 필터를 적용할때마다 …
=> [ Refactor ] 프롭스 줄이기, 필터 선택시 깜빡임 제거, 주석 제거

src/components/commons/ToggleButton.tsx, src/pages/juniorPromise/components/BottomSheetBg.tsx
Closes #231 
[x] 바텀시트 내부 버튼 사이즈 폭 조정
[x] 컨텐츠 간격 조정
다양한 사이즈에 대응하기 위해 구체적인 사이즈를 지정하는 것을 지양해야겠다는 생각이 들었어요!
1️⃣ 공통 컴포넌트(Toggle) 폭 수정
: 해당 컴포넌트는 지은, 예림 뷰에서만 사용되는 공통 컴포넌트입니다. 
지은 뷰에서 폭 100%로 수정하여 피그마 뷰와 일치 시켰고, 제 컴포넌트에서 별도의 레이아웃을 추가하여 조정 완료 했습니다!
2️⃣ 바텀시트 하단 버튼 폭 수정
: `width: 27.4rem;`
구체적인 사이즈를 지정한 기존의 코드를 삭제하고
아래의 내용으로 수정하여 피그마 뷰와 일치 시켰습니다!
`  flex-grow: 1;`
3️⃣ 바텀시트 내부 컨텐츠 간격 조정
: 기존 1rem을 피그마 뷰와 동일하게 1.5rem으로 수정하였습니다.
🍀 추가적으로 공통 토글 컴포넌트는 지은이 컴포넌트라 코리 페어는 아니지만 지은이도 코드리뷰어로 소환하였습니다! 
지은이는 1️⃣번의 내용만 확인해주시면 될 거 같습니당!
🍀 브랜치명이 적합하지 않다고 생각되어 머지할때 수정하겠습니다!
1️⃣,2️⃣,3️⃣번의 내용 모두 아래의 사진으로 확인해주시면 감사하겠습니다!
- 모바일 뷰에서의 바텀시트
- 모바일뷰 풀었을때
- 바텀시트 내부 핸들바 중앙정렬 사이즈별 동영상
https://github.com/user-attachments/assets/e7bc1196-130e-490f-9846-352a0216fd82
=> [Fix] 바텀시트 내부 버튼 폭 수정 및 컨텐츠 간격 조정

src/components/commons/Nav.tsx, src/pages/promiseList/components/PromiseTap.tsx
Closes #249 
- 선배 nav바 둘러보기 탭 클릭 막기
앱잼단에서 role 받아오기 전에 JUNIOR로 하드코딩해둔게 남아있어서 접근이 가능했더라구요. localStorage에서 받아오는 걸로 로직 변경했습니다
- promiseList 페이지 콘솔에 key값 중복 에러 나는 거 해결
기존에는 appointmentId + idx 로 key값을 부여했는데, 생각해보니까 appointmentId는 약속마다 고유하기 때문에 굳이 idx를 추가해서 만들어줄 필요가 없더라구요? 따라서 appointmentId로만 key부여했고, 중복 에러도 없어졌습니당!
- 선배 nav바 둘러보기 탭 클릭 막기
https://github.com/user-attachments/assets/5066f2eb-2603-4f27-98b5-09f0f152dfee
- promiseList 페이지 콘솔에 key값 중복 에러 나는 거 해결
기존
변경 후
https://github.com/user-attachments/assets/5b6b750d-b707-40b8-b118-7300924d7d1a
=> [ Fix/#249 ] 선배 nav바 둘러보기 탭 클릭 막기, promiseList 페이지 콘솔에 key값 중복 에러 나는 거 해결

src/pages/juniorPromise/JuniorPromisePage.tsx
Closes #263
`React Router caught the following error during render Error: Rendered more hooks than during the previous render.
`
이 에러는 이전 렌더링과 비교해서 현재 렌더링에서 더 많은 훅이 사용되었다는 것을 알려주는 것이라고 합니다!!
조건부로 훅을 호출하면 이런 에러가 발생할 수 있고, React에서 훅은 항상 동일한 순서로 호출되어야 한다고 하네요 
☀️ 아래 방법들로 해결할 수 있슴다~!
1. 모든 useState 훅을 컴포넌트 최상단으로 이동
2. 조건부 반환 (if (isLoading), if (isError))을 모든 훅 선언 이후로 이동
3. 데이터 처리 로직을 단순화하고 일관성 있게 배치
JuniorPromise 컴포넌트를 다음과 같이 재구성 하였습니다.
1. 모든 `useState` 상태 훅을 컴포넌트 최상단에 배치
2. `useSeniorProfileQueries` 호출을 조건부 렌더링 밖으로 이동
3. 모든 이벤트 핸들러와 상태 업데이트 함수를 상단에 정의
따라서 모든 훅이 일관된 순서로 호출되고, 조건부 렌더링이 훅의 호출에 영향을 미치지 않기 때문에 해결할 수 있습니다
해결 완료!!
https://github.com/user-attachments/assets/1d01cc0c-77f9-468e-94ff-3d4e89e49102
=> [ Fix ] junior promise 렌더링 에러 해결

src/pages/onboarding/components/Layout.tsx, src/pages/onboarding/components/commonOnboarding/Step계열선택.tsx, src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx
Closes #256 
> **앞선 PR과 동일하게 단순히 잘못된 route를 사용중이던 navigate path 값을 수정해준 작업입니다!** 
🤙🏻 **약관동의 뒤로가기 버튼 관련** 
약관동의 단계의 route가 ~Onboarding/1 인데요, navigate('~') 이런식으로 이동되는 다른 step들과 달리 해당 페이지는 
`/~Onboarding`으로 navigate 후 Navigate 컴포넌트를 사용해서 `/~Onboarding/1`로 이동하는 방식을 사용하고 있어요. 
```js
{
path: 'juniorOnboarding',
element: <Layout userRole="JUNIOR" />,
children: [
{
index: true,
element: <Navigate to="1" />,
},
{
path: '1',
element: <Step약관동의 />,
},
```
그래서 뒤로가기 버튼에 공통으로 적용시켜주고 있던 navigate(-1) 이 친구가 정상작동하지 않습니다. 
따라서 직접 navigate 시켜줄 path를 넣어야했는데요, 
엄밀히 따지면 뒤로가기 했을 때 아래처럼 생긴 SignupPage로 넘어가는게 순서상 맞으나, 
<Img src="https://github.com/user-attachments/assets/e4c01014-be3f-4d38-9757-6b0ae2aad161" width="200"/>
SignupPage에 별다른 뒤로가기 버튼이 없어서 선/후배 선택을 잘못했을 경우 재선택을 하지 못하게 돼요. 
따라서 그냥 SignupPage 말고 아예 최초 단계인 …
=> [ Fix ] navigate 오류 수정 2

src/pages/onboarding/components/commonOnboarding/Step개인정보입력.tsx, src/pages/onboarding/hooks/useNicknameQuery.ts
Closes #246 
[관련 커밋](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/commit/0e7662fe4c832de902408f3d82acdf381fb6aeb6) 
이미 존재하는 닉네임을 입력하고 중복확인을 눌러서 중복 에러가 발생하고 -> 이후 중복되지 않는 정상 닉네임으로 수정하고 다시 중복확인을 클릭했는데 -> API는 성공함에도 불구하고 에러박스는 유지되는 문제가 있었습니다. 
nickname 상태 관련 state를 isNicknameValid와 isNicknameError 이렇게 두개를 사용해주고 있었는데 
닉네임 중복체크 에러가 발생했을 때 setNicknameError(true)는 해주면서 setNicknameValid(false)는 해주지 않아서 생긴 문제였어요. 
그런데 이렇게 동일한 '닉네임의 유효성'에 대한 상태를 여러개의 state로 관리해주는게 좋지 못한 방식이라는 생각이 들었어요. 
그래서 하나의 state로 통합 관리 하도록 수정해주었습니다. 
대신 가능한 닉네임 유효성 상태가 여러개라서 기존처럼 boolean 타입을 사용하지는 못하구요 
- 유효함 : VALID
- 공백 (에러도 아니지만 유효하지도 않음) : EMPTY
- 에러 : (2번에서 부연설명) INVALID, CONFLICT
이렇게 문자열값으로 상태 관리 방식 수정하였습니다 
[관련 커밋](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/commit/866bb5e1d7ef463949c92f7b4ef80e41f22b7379) 
기존에 …
=> [ Fix ] 닉네임 중복체크 재검사 시 초기화 & 409에러 중복처리 

src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx, src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
Closes #254 
Closes #255 
> **단순히 잘못된 route를 사용중이던 navigate path 값을 수정해준 작업이라 가볍게 보셔도 됩니다!** 
1. 이미 가입된 번호 모달 - 로그인하러 가기 버튼 클릭 시 기존에는 존재하지 않는 Path로 이동해서 404가 터졌었는데요, 
곧바로 구글 로그인 페이지로 이동하도록 수정했습니다. 
2. 후배 온보딩 완료 시 alert가 뜨고, alert 확인을 누르면 404가 터졌었는데요, 불필요한 alert를 삭제했고 온보딩 완료 시 정상적인 path (/juniorOnboarding/complete) 로 이동할 수 있도록 수정해주었습니다. 
1번
https://github.com/user-attachments/assets/d0a5f619-2dfe-43dc-920f-efa328a56170
2번 
2번은 지금 가입할 수 있는 학생 이메일이 없어서 인증샷 생략합니다 , ,
=> [ Fix ] navigate 오류 수정 1

src/components/commons/ToggleButton.tsx, src/pages/juniorPromise/JuniorPromisePage.tsx, src/pages/juniorPromise/components/BottomSheet.tsx
Closes #244 
.
📣 feat~ 타입변경 커밋부터 확인해주시면 됩니다..!
1️⃣ `isBottomSheetOpen` 상태 제거
: 바텀시트를 열고 닫는 것을 관장하던 상태 제거
2️⃣ 공통 토글 버튼 타입 변경
: 담당자였던 지은이의 허락을 받고 변경했습니다..! 변경했을 때 별다른 오류는 없었습니다.
```
interface toggleButtonPropType {
left: string;
right: string;
activeButton: string | null;
onSetActiveButtonHandler: (button: string) => void;
}
```
activeButton에 null 을 추가해 
string일때는 string 내용에 맞는 바텀시트가 열리고(계열, 직무) 
null일때는 닫히도록 구현하였습니다.
3️⃣ 해당 로직을 `filterActiveBtn` 를 활용해 변경  
`const [filterActiveBtn, setFilterActiveBtn] = useState<string | null>(null);
`
: 기존 isBottomSheetOpen을 활용했던 로직을 위의 상태를 이용해 모두 변경했습니다!
4️⃣ 이전 리팩토링 과정에서 해당로직을 handleChipField, handleChipPosition으로 수정했는데 기존의 사용하던 함수를 지우지 않았더라구요,, 미사용 함수 제거 했습니다..!
변경 이후 에러 없는 화면입니다!
https://github.com/user-attachments/assets/93676735-6576-450f-9586-967077dd …
=> [ Refactor ] junior propmise page isBottomSheetOpen프롭스 제거

src/pages/promiseDetail/PromiseDetailPage.tsx, src/pages/promiseDetail/PromiseDetailPageJunior.tsx, src/pages/promiseList/components/ProfileContainer.tsx, src/pages/promiseList/components/PromiseTap.tsx
Closes #267 
없
- 약속 디테일 페이지에 들어갔다가 뒤로가기 하면 매번 확정대기 탭으로 이동되던 이슈가 있었는데, 사용자가 이전에 남아있던 탭 기억해서 반영하도록 작업해두었습니다.
- `약속 리스트 페이지`에서 약속 컨테이너 클릭시, 어느 탭에서 눌린 건지 navigate의 state로 전달하는 로직이 있습니다.
```typescript
// ProfileContainer.tsx
// 상세 페이지 라우팅
const handleClickProfileContainer = (tap: string, userRole: string) => {
if (userRole === 'SENIOR' && tap === 'pending') {
navigate('/promiseList/promiseDetail', {
// ✅✅✅ 요부분!! ✅✅✅
state: { tap: 'pending', myNickname: myNickname, appointmentId: profileCardData?.appointmentId },
});
}
if (userRole === 'JUNIOR' && tap === 'pending') {
navigate('/promiseList/promiseDetailJunior', {
// ✅✅✅ 요부분!! ✅✅✅
state: {
tap: 'pending',
myNickname,
appointmentId: profileCardData?.appointmentId,
seniorId: profileCardData?.seniorId,
},
});
}
if (userRole === 'SENIOR' && (tap …
```
=> [ Fix ] 약속리스트 변경된 라우터 반영 / 이전탭 남아있도록 수정

src/App.tsx, src/components/commons/Header.tsx, src/components/commons/seniorCard/SeniorCard.tsx, src/pages/promiseDetail/PromiseDetailPage.tsx, src/pages/promiseDetail/PromiseDetailPageJunior.tsx
Closes #265 
없
- 자잘한 레이아웃 수정했습니다. (헤더 아래 구분선 , 헤더와의 간격 조정 등)
- 진이가 만들어둔 `Preview` 컴포넌트의 `SeniorCard` 컴포넌트에서 회사명에 랜덤색상 부여하는 부분이있는데요
- 해당 컴포넌트는 상위 컴포넌트에서 구글밋 입장 시간 계산하는 함수 때문에 1초마다 리렌더링이 일어나는데, 그것때문에 1초마다 색상이 바뀌는 이슈가 발생했어요
- 때문에 state로 관리하여 변하지 않도록 해두었습니다.
```typescript
// index.ts > Preview > SeniorCard 컴포넌트
const [randomColor] = useState(Math.floor(Math.random() * 3));
```
-> 하위 컴포넌트에서는 1초마다 리렌더링이 발생하지 않도록 memo같은 거 써서 최적화 해야할 것 같은데, 더 알아보고 하려고 우선은 깜빡이는 부분만 수정해두었어요
이전
https://github.com/user-attachments/assets/f324d1be-14c1-4c2e-ba17-64908bd024e4
이후
https://github.com/user-attachments/assets/a3a08bbd-8af8-4ba5-9190-8206e3327d69
=> [ Fix ] 약속리스트 페이지 레이아웃 조정 / 선배 상세정보(Preview 컴포넌트) 회사 색상 깜빡이는 이슈 수정

src/pages/juniorPromiseRequest/components/RequestComplete.tsx
Closes #285 
- [x] 후배 약속신청 확인 모달 위치 수정
left:0 으로 왼쪽에 붙어있던 모달 페이지를 가운데로 옮겨줬습니다
- 이전 뷰
- 고친 뷰
=> [ Design ] 후배 약속신청 확인 모달 위치 수정

src/pages/onboarding/components/Layout.tsx
Closes #272 
최초에 QA시 발견했던 문제는 다른 단계에서 학과 선택 단계로 돌아왔을 때 API 400에러가 뜬다! 였어요 
근데 일반적으로 다음 단계로 넘어간 후 단계를 돌아왔을 때는 같은 문제가 발생하지 않더라고요? 
문제가 발생하는 경우는 **온보딩 중간에 리로드(새로고침)을 했을 때** 였어요! 
에러나는 모습은 이러한데, 
400에러가 나는 이유는 학과 리스트 조회 API에서 univName에 정상적인 parameter가 들어가지 않았기 때문이에요. 
parameter 변수에 들어가는 데이터가 온보딩 단계 전체를 감싸는 `OutletContext`에서 들고다니는 univName 값인데요, 
이 값을 출력해보니 아무것도 출력되지 않더라고요! (undefined) 
그래서 context로 들고다니는 모든 데이터를 출력해보니까, univName 외의 모든 데이터가 초기화된 것을 볼 수 있었어요
이렇게 데이터가 초기화된 이유는 리로드(새로고침)이 발생했기 때문이에요. 
원래의 일반적인 경우엔, 이렇게 새로고침을 통해 들고다니던 상태값이 초기화될 경우, 첫 단계로 튕겨져 나가서 다시 처음부터 작성하도록 유도해야 하는데, 
저희 서비스 같은 경우엔 각 온보딩 단계가 funnel 구조가 아닌 **각기다른 URL로 분리** 되어있어서 데이터가 다 날아감에도 불구하고 진행중인 단계의 화면은 유지되어요. 그럼 사용자는 앞단의 데이터가 잘 보관되고 있다고 착각할 수 있겠죠? 
그래서 이 문제에 대한 해결책으로, **온보딩 과정 중에 새로고침이 발생했을 경우엔 무조건 1단계로 사용자를 보내버리기!** 를 …
=> [ Fix ] 온보딩 중 새로고침 시 1단계로 navigate

src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx
Closes #268 
activeButton이 '작성할래요'인 경우 personalTopic의 조건부 코드에 오류가 있던 것을 발견했습니다.
따라서 activeButton이 '작성할래요'인 경우, personalTopic을 inputVal을 가지도록 하고, '선택할래요'인 경우에는 personalTopic에 빈 문자열을 가지도록 올바르게 수정했습니다.
첫번째 콘솔 : 토글 버튼이 '작성할래요'인 경우 텍스트 문자열만 전송됨.
두번째 콘솔: 토글 버튼이 '선택할래요'인 경우 선택한 고민 배열만 전송됨.
> 400 오류는 이미 약속 신청한 선배인 경우라 발생했습니다!
=> [ Fix ] 약속신청 사유 하나만 가도록 수정

src/pages/juniorPromiseRequest/JuniorPromiseRequestPage.tsx, src/pages/juniorPromiseRequest/components/WorryButtons.tsx, src/pages/juniorPromiseRequest/components/WorryTextarea.tsx
Closes #275 
.trim()을 사용해서 공백이 하나건 두개건 이게 공백인지 아닌지 쉽게 검사할 수 있다!
` const [isTextareaFilled, setIsTextareaFilled] = useState(false); `대신에  `const isTextareaFilled = inputVal.trim() !== '';`으로 inputVal이 공백인지 아닌지 검사하도록 수정했습니다!!
- 빈 공백만 있는 경우: 약속 신청하기 버튼 불이 안켜짐.
- 한 글자라도 있는 경우: 약속 신청하기 버튼에 불이 켜짐.
=> [ Fix ] 빈 문자열로 약속신청 하는 경우 막기

src/components/commons/seniorCard/SeniorCard.tsx, src/pages/seniorProfile/SeniorProfilePage.tsx, src/pages/seniorProfile/components/Example.tsx, src/pages/seniorProfile/components/preView/Review.tsx
Closes #294 
- 데이터 연결하는 부분은 온보딩을 거칠 수가 없어서 (이미 가입된 계정이라) 스크린샷을 남길 수가 없습니당
- 헤더 구분선 추가 및 content 간격 조정
- 리뷰보기 중앙정렬
=> [ Feat ] 온보딩, 선배프로필 등록 데이터 연결 및 디자인 QA 반영

src/pages/onboarding/components/Layout.tsx, src/pages/onboarding/components/juniorOnboarding/StepComplete.tsx
Closes #313 
예림언니가 제보해준 후배 온보딩 완료 뷰 모습인데요 
원인을 찾아보니 후배 온보딩 완료 뷰가 원래 별도의 페이지로 있었다가, 
url 정리하는 과정에서 `<Layout/>` 컴포넌트의 children들 (다른 step들과 같이)로 넣어주면서 
다른 온보딩 뷰들처럼 헤더와 제목이 자동으로 적용돼서 레이아웃이 밀린 문제였어요! 
그래서 Layout 컴포넌트에서 `location.pathname` 검사해서 
후배 온보딩 뷰일 경우, 감싸고있는 Wrapper들 다 제외하고 Outlet 만 return 할 수 있도록 조건부 렌더링 추가해서 해결해주었습니다! 
추가로 
- 피그마 확인해보니 해당 뷰 라이팅이 달라져있길래 이 부분도 반영했구, 
- 자동 navigate 처리도 누락되어있길래 추가해주었습니다! 
학교 이메일 인증이 막혀있는 이슈로 후배 온보딩 뒷부분 QA가 부족했네요... 🥲 담부터 더 꼼꼼히 보겠습니당 
https://github.com/user-attachments/assets/0291d734-4f62-49d3-b8e9-0ebb74a6e16a
=> [ Fix ] 후배 온보딩 완료 뷰 개선 

src/pages/juniorPromiseRequest/components/CalendarBottomBar.tsx, src/pages/juniorPromiseRequest/components/CalendarBottomSheet.tsx
Closes #306 
```
left: 50%
transform: translate(-50%, -50%);
```
해당 코드로 가운데 정렬을 해줬습니다
휴대폰에서만 밀림 현상이 발생해서 배포 후 폰으로 확인할 수 있을 것 같습니다!!!
=> [ Fix ] 휴대폰에서 캘린더 바텀시트 밀리는 현상 해결

src/pages/onboarding/apis/univAxios.ts, src/pages/onboarding/components/juniorOnboarding/Step이메일입력.tsx, src/pages/onboarding/hooks/useUnivQuery.ts
Closes #331 
기존에 사용하던 Open API가 **한번 사용한 메일주소는 재사용하지 못하는 이슈**로 테스트환경에 매우 부적합했는데요,
그래서 서버 측에서 `학교명 - 학교메일주소도메인` 데이터를 DB에 직접 넣어서 검증하는 방식으로 API가 수정되었습니다 
그 과정에서 API 살짝 바뀌어서 해당 변경사항 반영해주었고, 
작업 후 학교 메일 인증 정상적으로 이루어지는지도 테스트 완료했습니다! (아래 영상 참고) 
이제 후배 온보딩 끝까지 갈 수 있다 ! 야호 ! 🎉 
https://github.com/user-attachments/assets/36f4017b-57f4-4764-85c0-676c4db52249
=> [ Fix ] 후배 학교 메일 인증 API 변경사항 반영

src/pages/login/hooks/useGoogleLoginMutation.ts, src/utils/apis/index.ts, src/utils/storage.ts
Closes #330 
localStorage에 저장되어있는 토큰에 문제가 있을 경우, 저장되어있는 토큰/role 정보를 모두 삭제해주는 함수를 유틸함수에 추가해놨습니다! 
기존에는 회원가입이 아닌 로그인인데 서버에서 응답으로 role을 안넘겨줬을 경우, 서버 로직 상의 오류로 판단해서 그냥 console.error만 찍어두게 해놨었는데요, 생각해보니 해당 케이스가 충분히 사용자 단에서도 발생할 수 있는 케이스더라구요. 
저희가 로직상, **사용자가 온보딩을 시작하면 무조건 localStorage에 발급된 토큰이 저장**되는데요, 그러다가 **온보딩 중간에 이탈**하는 경우 
- 사용자의 localStorage에는 토큰이 저장되어있는데 
- DB에 회원으로는 들어가있지 않은 
상황이 돼요. 그 상황에서 사용자가 회원가입이 아닌 `로그인`을 시도하면 서버에서 role을 응답받지 못해서 해당 케이스로 빠져버리게 됩니다. 
이런 경우 저장되어있던 **가입 완료되지 않은 토큰을 삭제**해주고, 다시 **회원가입을 유도**해야 해요. 
따라서 `1) 회원가입 유도 alert` `2) clear Storage` `3) 최초 페이지로 이동` 시켜주도록 구현해놨습니다. 
(괵에게 전달 완료!)  
만료된 토큰으로 authAxios를 쓸 경우, 즉 만료된 토큰을 헤더에 넣어서 api 통신을 요청한 경우, 아래와 같은 에러가 발생해요. 
따라서 `axios.interceptors.response` 를 통해 API 응답에 에러를 캐치해서, 에러 code가 `40076`일 때만 만료 토큰 처리를 해주도록 구현했어요. 
> …
=> [ Feat ] 로그인 관련 에러 처리 (존재하지 않는 회원일 경우, 토큰 만료)

src/pages/errorPage/ErrorPage.tsx
Closes #321 
1️⃣ 변경된 피그마 뷰에 맞게 변경완료했습니다.
2️⃣ 홈이동 버튼 클릭시 로컬스토리지를 비우고 루트path로 이동하도록 구현했습니다.
3️⃣ 새로운 창으로 고객센터, 자주묻는질문 링크로 이동하도록 구현했습니다.
1️⃣
- SE 사이즈
- 데탑
<br/>
2️⃣ 홈이동구현(오른쪽 로컬스토리지 참고)
https://github.com/user-attachments/assets/60c93a12-78df-4af0-bb31-e672fe000ed4
3️⃣
- 고객센터이동
https://github.com/user-attachments/assets/dfce1b21-26a5-4ac8-91ff-41a64f20c4c2
- 자주묻는질문 이동
https://github.com/user-attachments/assets/431e6e61-fde8-4af5-a5f7-cfde92c65aa7
=> [ Feat ] 에러페이지 변경사항 적용

src/pages/juniorPromiseRequest/components/CalendarBottomSheet.tsx
Closes #334 
크롬과 사파리 모두 특정 버전 이후부터는 스크롤 시 주소창과 하단 바가 자동으로 숨겨지는 기능을 가지고 있었습니다.!
모바일 웹 스크롤 시 하단바에 가려지던 바텀바가 가려지지 않도록 수정했습니다.
height : 100vh 대신  height : auto 와 min-height: 100dvh를 사용해서,
전체화면으로 스크롤되도록 하여 해결했습니다!
- 하단바 있을 경우
- 하단바 없을 경우
=> [ Fix ] 모바일뷰 캘린더 하단바 안가려지게 수정

src/components/commons/Nav.tsx, src/pages/promiseDetail/PromiseDetailPageJunior.tsx, src/pages/promiseList/components/PromiseTap.tsx
Closes #308 
[지난번에 작업한 내용인데요](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/pull/269)
선배일 경우만 남아있도록 작업해두고 후배일 경우에는 작업을 안해뒀길래 해당 부분 추가해두었습니다!
[이전]
https://github.com/user-attachments/assets/d3f1d8f5-56ed-4a3c-bee0-61879d7f50e2
[이후]
https://github.com/user-attachments/assets/3cdf0f25-0fa0-44dd-8b88-af5607c676f2
=> [ Fix ] 약속 리스트 후배일 경우 뒤로가기 탭 남아있도록 하기

src/components/commons/Nav.tsx
Closes #337 
선후배 Nav바 순서가 다르더라구요 
선배
둘러보기 / 나의약속 / 마이페이지
후배
나의약속 / 둘러보기 / 마이페이지
반영해두었습니다.
- 선배
https://github.com/user-attachments/assets/531fa311-4209-4604-882f-11f7594b02d1
- 후배
https://github.com/user-attachments/assets/602bac61-bf3a-40c2-8a61-43fe18b8bc39
=> [ Fix ] 선후배 Nav바 다른 거 반영

src/pages/onboarding/components/commonOnboarding/Step번호입력.tsx, src/pages/onboarding/hooks/useJoinQuery.ts, src/pages/promiseList/PromiseListPage.tsx
Closes #309 
롤이 안 받아와져서 봤더니 필드면이 userType이더라구요 
role로 파싱해서 받아오고 있었던 이슈!
숭 부분이라 같이 태그함다~
롤 저장되는 걸 녹화하려면 서버에게 절 디비에서 죽여달라고 해야해서 .. 저장된 거 캡쳐합니다 . . .
=> [ Fix ] 가입시 Role 받아오는 로직 수정
